version: '3'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./database.db:/db/database.db