name: Run tests on any Push event
on:
  push:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Docker-Deploy 
        run: | # Going to remove this for testing
            docker-compose -f docker-compose.yml up --build -d
            docker-compose up &
      - name: Install Requirements
        run: |
            python3.9 -m pip install -r requirements.txt
      - name: Run tests
        run: python3.9 -m pytest tests/Bio-KeyAPI-test.py