name: Run tests on any Push event
on:
  push:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        name: Checkout
#      - name: Build Docker Container
#        run: |
#             docker-compose -f docker-compose.yml up --build -d &
      - uses: actions/setup-python@v5
        name: Setup Python
        with:
            python-version: '3.9'
            cache: 'pip'
      - name: Install Requirements
        run: |
             pip install -r requirements.txt
      - uses: hoverkraft-tech/compose-action@v1.5.1
        name: Docker Compose
        with:
             compose-file: "./docker/docker-compose.yml"
      - name: Run tests
        run: python -m pytest BioKey-Tests.py