name: Run tests on any Push event
on:
  push:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        name: CheckOut Repository
      - name: Build Docker Container
        run: |
          docker-compose -f docker-compose.yml up --build -d &
      - uses: actions/setup-python@v4
        with:
            python-version: '3.9'
      - name: Install Requirements
        run: |
            python -m pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest BioKey-Tests.py